#pragma once
#include "includes.hpp"
#include "nodes/access/access.hpp"
#include "nodes/evaluation/literals/char.hpp"
#include "nodes/evaluation/specials/array_allocation.hpp"
#include "nodes/statements/switch.hpp"
#include "nodes/structures/enum.hpp"
#include "nodes/subprogram/call.hpp"
#include "references/references.hpp"